# Generated by Django 4.2 on 2023-05-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posevideo',
            name='original_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
